{{- if .Values.executor.enabled }}
{{- $executorSecret := include "appwrite.executorSecret" . }}
---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "appwrite.fullname" $ }}-executor-env"
  labels:
{{ include "appwrite.labels" $ | indent 4 }}
type: Opaque
data:
  OPR_EXECUTOR_SECRET: {{ $executorSecret | b64enc }}
  _APP_EXECUTOR_SECRET: {{ $executorSecret | b64enc }}
  {{- if .Values.executor.dockerHub.password }}
  OPR_EXECUTOR_DOCKER_HUB_PASSWORD: {{ .Values.executor.dockerHub.password | b64enc }}
  {{- end }}
{{- end }}
