---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "appwrite.fullname" $ }}-redis-env"
  labels:
{{ include "appwrite.labels" $ | indent 4 }}
type: Opaque
stringData:
  _APP_REDIS_USER: {{ .Values.redis.auth.username | default "" | quote }}
  _APP_REDIS_PASS: {{ .Values.redis.auth.password | default "" | quote }}
  _APP_REDIS_HOST: {{ include "appwrite.fullname" . | printf "%s-redis-master" | quote }}
  _APP_REDIS_PORT: "6379"
